server:
  port: ${SERVER_PORT:8181}
  servlet:
    session:
      cookie:
        http-only: true
        secure: false
  error:
    include-message: always
    include-stacktrace: ${SERVER_STACKTRACE:never}
    include-binding-errors: always
    include-exception: false

###################################  Config LOG Transaction ##############################
log4j:
  logger:
    org:
      hibernate:
        SQL: debug
        type: trace

###################################  MySQL Database as persistent Database  ##############################
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sampleprojecttech?autoReconnect=true&useSSL=false&tinyInt1isBit=false&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf-8
    username: ${DB_USER:root}
    password: ${DB_PASS:admin}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      SQL: DEBUG
      ddl-auto: update
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        format_sql: true
